micronaut:
  application:
    name: cursokotlin
  server:
    port: 8081

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    leak-detection-threshold: 60000
    connection-test-query: SELECT 1

#  default:
#    url: jdbc:mariadb://localhost:3306/
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: '123'

#  h2:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true
