micronaut:
  application:
    name: cursokotlin

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: '123'

#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

#jpa:
#  default:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        show_sql: true
